<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Radacct', 'doctrine');

/**
 * BaseRadacct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $acctsessionid
 * @property string $acctuniqueid
 * @property string $username
 * @property string $groupname
 * @property string $realm
 * @property inet $nasipaddress
 * @property string $nasportid
 * @property string $nasporttype
 * @property timestamp $acctstarttime
 * @property timestamp $acctstoptime
 * @property integer $acctsessiontime
 * @property string $acctauthentic
 * @property string $connectinfo_start
 * @property string $connectinfo_stop
 * @property integer $acctinputoctets
 * @property integer $acctoutputoctets
 * @property string $calledstationid
 * @property string $callingstationid
 * @property string $acctterminatecause
 * @property string $servicetype
 * @property string $framedprotocol
 * @property inet $framedipaddress
 * @property integer $acctstartdelay
 * @property integer $acctstopdelay
 * @property string $xascendsessionsvrkey
 * 
 * @method integer   getId()                   Returns the current record's "id" value
 * @method string    getAcctsessionid()        Returns the current record's "acctsessionid" value
 * @method string    getAcctuniqueid()         Returns the current record's "acctuniqueid" value
 * @method string    getUsername()             Returns the current record's "username" value
 * @method string    getGroupname()            Returns the current record's "groupname" value
 * @method string    getRealm()                Returns the current record's "realm" value
 * @method inet      getNasipaddress()         Returns the current record's "nasipaddress" value
 * @method string    getNasportid()            Returns the current record's "nasportid" value
 * @method string    getNasporttype()          Returns the current record's "nasporttype" value
 * @method timestamp getAcctstarttime()        Returns the current record's "acctstarttime" value
 * @method timestamp getAcctstoptime()         Returns the current record's "acctstoptime" value
 * @method integer   getAcctsessiontime()      Returns the current record's "acctsessiontime" value
 * @method string    getAcctauthentic()        Returns the current record's "acctauthentic" value
 * @method string    getConnectinfoStart()     Returns the current record's "connectinfo_start" value
 * @method string    getConnectinfoStop()      Returns the current record's "connectinfo_stop" value
 * @method integer   getAcctinputoctets()      Returns the current record's "acctinputoctets" value
 * @method integer   getAcctoutputoctets()     Returns the current record's "acctoutputoctets" value
 * @method string    getCalledstationid()      Returns the current record's "calledstationid" value
 * @method string    getCallingstationid()     Returns the current record's "callingstationid" value
 * @method string    getAcctterminatecause()   Returns the current record's "acctterminatecause" value
 * @method string    getServicetype()          Returns the current record's "servicetype" value
 * @method string    getFramedprotocol()       Returns the current record's "framedprotocol" value
 * @method inet      getFramedipaddress()      Returns the current record's "framedipaddress" value
 * @method integer   getAcctstartdelay()       Returns the current record's "acctstartdelay" value
 * @method integer   getAcctstopdelay()        Returns the current record's "acctstopdelay" value
 * @method string    getXascendsessionsvrkey() Returns the current record's "xascendsessionsvrkey" value
 * @method Radacct   setId()                   Sets the current record's "id" value
 * @method Radacct   setAcctsessionid()        Sets the current record's "acctsessionid" value
 * @method Radacct   setAcctuniqueid()         Sets the current record's "acctuniqueid" value
 * @method Radacct   setUsername()             Sets the current record's "username" value
 * @method Radacct   setGroupname()            Sets the current record's "groupname" value
 * @method Radacct   setRealm()                Sets the current record's "realm" value
 * @method Radacct   setNasipaddress()         Sets the current record's "nasipaddress" value
 * @method Radacct   setNasportid()            Sets the current record's "nasportid" value
 * @method Radacct   setNasporttype()          Sets the current record's "nasporttype" value
 * @method Radacct   setAcctstarttime()        Sets the current record's "acctstarttime" value
 * @method Radacct   setAcctstoptime()         Sets the current record's "acctstoptime" value
 * @method Radacct   setAcctsessiontime()      Sets the current record's "acctsessiontime" value
 * @method Radacct   setAcctauthentic()        Sets the current record's "acctauthentic" value
 * @method Radacct   setConnectinfoStart()     Sets the current record's "connectinfo_start" value
 * @method Radacct   setConnectinfoStop()      Sets the current record's "connectinfo_stop" value
 * @method Radacct   setAcctinputoctets()      Sets the current record's "acctinputoctets" value
 * @method Radacct   setAcctoutputoctets()     Sets the current record's "acctoutputoctets" value
 * @method Radacct   setCalledstationid()      Sets the current record's "calledstationid" value
 * @method Radacct   setCallingstationid()     Sets the current record's "callingstationid" value
 * @method Radacct   setAcctterminatecause()   Sets the current record's "acctterminatecause" value
 * @method Radacct   setServicetype()          Sets the current record's "servicetype" value
 * @method Radacct   setFramedprotocol()       Sets the current record's "framedprotocol" value
 * @method Radacct   setFramedipaddress()      Sets the current record's "framedipaddress" value
 * @method Radacct   setAcctstartdelay()       Sets the current record's "acctstartdelay" value
 * @method Radacct   setAcctstopdelay()        Sets the current record's "acctstopdelay" value
 * @method Radacct   setXascendsessionsvrkey() Sets the current record's "xascendsessionsvrkey" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRadacct extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('radacct');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'radacct_radacctid',
             'length' => 8,
             ));
        $this->hasColumn('acctsessionid', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('acctuniqueid', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('username', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('groupname', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('realm', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nasipaddress', 'inet', null, array(
             'type' => 'inet',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nasportid', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nasporttype', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('acctstarttime', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('acctstoptime', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('acctsessiontime', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('acctauthentic', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('connectinfo_start', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('connectinfo_stop', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('acctinputoctets', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'default' => '0',
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('acctoutputoctets', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'default' => '0',
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('calledstationid', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('callingstationid', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('acctterminatecause', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('servicetype', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('framedprotocol', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('framedipaddress', 'inet', null, array(
             'type' => 'inet',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('acctstartdelay', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('acctstopdelay', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('xascendsessionsvrkey', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}