<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AccAccseries', 'doctrine');

/**
 * BaseAccAccseries
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_usagedefinition
 * @property integer $id_isporg
 * @property integer $id_systemuser
 * @property timestamp $crdate
 * @property decimal $nraccount
 * @property string $acctype
 * @property decimal $pst_commission
 * @property integer $id_ispsuborg
 * @property AccIsporg $AccIsporg
 * @property AccUsagedefinition $AccUsagedefinition
 * @property AccSystemuser $AccSystemuser
 * @property AccIspsuborg $AccIspsuborg
 * @property Doctrine_Collection $AccPostpaccount
 * @property Doctrine_Collection $AccPrepaccount
 * @property Doctrine_Collection $AccSubscriberinfo
 * @property Doctrine_Collection $Radcheck
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method integer             getIdUsagedefinition()  Returns the current record's "id_usagedefinition" value
 * @method integer             getIdIsporg()           Returns the current record's "id_isporg" value
 * @method integer             getIdSystemuser()       Returns the current record's "id_systemuser" value
 * @method timestamp           getCrdate()             Returns the current record's "crdate" value
 * @method decimal             getNraccount()          Returns the current record's "nraccount" value
 * @method string              getAcctype()            Returns the current record's "acctype" value
 * @method decimal             getPstCommission()      Returns the current record's "pst_commission" value
 * @method integer             getIdIspsuborg()        Returns the current record's "id_ispsuborg" value
 * @method AccIsporg           getAccIsporg()          Returns the current record's "AccIsporg" value
 * @method AccUsagedefinition  getAccUsagedefinition() Returns the current record's "AccUsagedefinition" value
 * @method AccSystemuser       getAccSystemuser()      Returns the current record's "AccSystemuser" value
 * @method AccIspsuborg        getAccIspsuborg()       Returns the current record's "AccIspsuborg" value
 * @method Doctrine_Collection getAccPostpaccount()    Returns the current record's "AccPostpaccount" collection
 * @method Doctrine_Collection getAccPrepaccount()     Returns the current record's "AccPrepaccount" collection
 * @method Doctrine_Collection getAccSubscriberinfo()  Returns the current record's "AccSubscriberinfo" collection
 * @method Doctrine_Collection getRadcheck()           Returns the current record's "Radcheck" collection
 * @method AccAccseries        setId()                 Sets the current record's "id" value
 * @method AccAccseries        setIdUsagedefinition()  Sets the current record's "id_usagedefinition" value
 * @method AccAccseries        setIdIsporg()           Sets the current record's "id_isporg" value
 * @method AccAccseries        setIdSystemuser()       Sets the current record's "id_systemuser" value
 * @method AccAccseries        setCrdate()             Sets the current record's "crdate" value
 * @method AccAccseries        setNraccount()          Sets the current record's "nraccount" value
 * @method AccAccseries        setAcctype()            Sets the current record's "acctype" value
 * @method AccAccseries        setPstCommission()      Sets the current record's "pst_commission" value
 * @method AccAccseries        setIdIspsuborg()        Sets the current record's "id_ispsuborg" value
 * @method AccAccseries        setAccIsporg()          Sets the current record's "AccIsporg" value
 * @method AccAccseries        setAccUsagedefinition() Sets the current record's "AccUsagedefinition" value
 * @method AccAccseries        setAccSystemuser()      Sets the current record's "AccSystemuser" value
 * @method AccAccseries        setAccIspsuborg()       Sets the current record's "AccIspsuborg" value
 * @method AccAccseries        setAccPostpaccount()    Sets the current record's "AccPostpaccount" collection
 * @method AccAccseries        setAccPrepaccount()     Sets the current record's "AccPrepaccount" collection
 * @method AccAccseries        setAccSubscriberinfo()  Sets the current record's "AccSubscriberinfo" collection
 * @method AccAccseries        setRadcheck()           Sets the current record's "Radcheck" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAccAccseries extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('acc_accseries');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'acc_accseries_id',
             'length' => 4,
             ));
        $this->hasColumn('id_usagedefinition', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_isporg', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_systemuser', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('crdate', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('nraccount', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('acctype', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('pst_commission', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'default' => '0',
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('id_ispsuborg', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AccIsporg', array(
             'local' => 'id_isporg',
             'foreign' => 'id'));

        $this->hasOne('AccUsagedefinition', array(
             'local' => 'id_usagedefinition',
             'foreign' => 'id'));

        $this->hasOne('AccSystemuser', array(
             'local' => 'id_systemuser',
             'foreign' => 'id'));

        $this->hasOne('AccIspsuborg', array(
             'local' => 'id_ispsuborg',
             'foreign' => 'id'));

        $this->hasMany('AccPostpaccount', array(
             'local' => 'id',
             'foreign' => 'id_accseries'));

        $this->hasMany('AccPrepaccount', array(
             'local' => 'id',
             'foreign' => 'id_accseries'));

        $this->hasMany('AccSubscriberinfo', array(
             'local' => 'id',
             'foreign' => 'id_accseries'));

        $this->hasMany('Radcheck', array(
             'local' => 'id',
             'foreign' => 'id_accseries'));
    }
}