<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Radpostauth', 'doctrine');

/**
 * BaseRadpostauth
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $username
 * @property string $pass
 * @property string $reply
 * @property string $calledstationid
 * @property string $callingstationid
 * @property timestamp $authdate
 * 
 * @method integer     getId()               Returns the current record's "id" value
 * @method string      getUsername()         Returns the current record's "username" value
 * @method string      getPass()             Returns the current record's "pass" value
 * @method string      getReply()            Returns the current record's "reply" value
 * @method string      getCalledstationid()  Returns the current record's "calledstationid" value
 * @method string      getCallingstationid() Returns the current record's "callingstationid" value
 * @method timestamp   getAuthdate()         Returns the current record's "authdate" value
 * @method Radpostauth setId()               Sets the current record's "id" value
 * @method Radpostauth setUsername()         Sets the current record's "username" value
 * @method Radpostauth setPass()             Sets the current record's "pass" value
 * @method Radpostauth setReply()            Sets the current record's "reply" value
 * @method Radpostauth setCalledstationid()  Sets the current record's "calledstationid" value
 * @method Radpostauth setCallingstationid() Sets the current record's "callingstationid" value
 * @method Radpostauth setAuthdate()         Sets the current record's "authdate" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRadpostauth extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('radpostauth');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'radpostauth_id',
             'length' => 8,
             ));
        $this->hasColumn('username', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('pass', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('reply', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('calledstationid', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('callingstationid', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('authdate', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}