<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AccSystemuser', 'doctrine');

/**
 * BaseAccSystemuser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $username
 * @property string $pass
 * @property string $acctype
 * @property integer $id_isporg
 * @property integer $id_ispsuborg
 * @property string $name
 * @property string $email
 * @property string $phone
 * @property string $mobile
 * @property string $lang
 * @property AccIsporg $AccIsporg
 * @property AccIspsuborg $AccIspsuborg
 * @property Doctrine_Collection $AccAccseries
 * @property Doctrine_Collection $AccPostpaccountlog
 * @property Doctrine_Collection $AccPrepaccount
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method string              getUsername()           Returns the current record's "username" value
 * @method string              getPass()               Returns the current record's "pass" value
 * @method string              getAcctype()            Returns the current record's "acctype" value
 * @method integer             getIdIsporg()           Returns the current record's "id_isporg" value
 * @method integer             getIdIspsuborg()        Returns the current record's "id_ispsuborg" value
 * @method string              getName()               Returns the current record's "name" value
 * @method string              getEmail()              Returns the current record's "email" value
 * @method string              getPhone()              Returns the current record's "phone" value
 * @method string              getMobile()             Returns the current record's "mobile" value
 * @method string              getLang()               Returns the current record's "lang" value
 * @method AccIsporg           getAccIsporg()          Returns the current record's "AccIsporg" value
 * @method AccIspsuborg        getAccIspsuborg()       Returns the current record's "AccIspsuborg" value
 * @method Doctrine_Collection getAccAccseries()       Returns the current record's "AccAccseries" collection
 * @method Doctrine_Collection getAccPostpaccountlog() Returns the current record's "AccPostpaccountlog" collection
 * @method Doctrine_Collection getAccPrepaccount()     Returns the current record's "AccPrepaccount" collection
 * @method AccSystemuser       setId()                 Sets the current record's "id" value
 * @method AccSystemuser       setUsername()           Sets the current record's "username" value
 * @method AccSystemuser       setPass()               Sets the current record's "pass" value
 * @method AccSystemuser       setAcctype()            Sets the current record's "acctype" value
 * @method AccSystemuser       setIdIsporg()           Sets the current record's "id_isporg" value
 * @method AccSystemuser       setIdIspsuborg()        Sets the current record's "id_ispsuborg" value
 * @method AccSystemuser       setName()               Sets the current record's "name" value
 * @method AccSystemuser       setEmail()              Sets the current record's "email" value
 * @method AccSystemuser       setPhone()              Sets the current record's "phone" value
 * @method AccSystemuser       setMobile()             Sets the current record's "mobile" value
 * @method AccSystemuser       setLang()               Sets the current record's "lang" value
 * @method AccSystemuser       setAccIsporg()          Sets the current record's "AccIsporg" value
 * @method AccSystemuser       setAccIspsuborg()       Sets the current record's "AccIspsuborg" value
 * @method AccSystemuser       setAccAccseries()       Sets the current record's "AccAccseries" collection
 * @method AccSystemuser       setAccPostpaccountlog() Sets the current record's "AccPostpaccountlog" collection
 * @method AccSystemuser       setAccPrepaccount()     Sets the current record's "AccPrepaccount" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAccSystemuser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('acc_systemuser');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'acc_systemuser_id',
             'length' => 4,
             ));
        $this->hasColumn('username', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('pass', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('acctype', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('id_isporg', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_ispsuborg', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('email', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('phone', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('mobile', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('lang', 'string', null, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AccIsporg', array(
             'local' => 'id_isporg',
             'foreign' => 'id'));

        $this->hasOne('AccIspsuborg', array(
             'local' => 'id_ispsuborg',
             'foreign' => 'id'));

        $this->hasMany('AccAccseries', array(
             'local' => 'id',
             'foreign' => 'id_systemuser'));

        $this->hasMany('AccPostpaccountlog', array(
             'local' => 'id',
             'foreign' => 'id_systemuser'));

        $this->hasMany('AccPrepaccount', array(
             'local' => 'id',
             'foreign' => 'id_systemuser'));
    }
}