<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Radcheck', 'doctrine');

/**
 * BaseRadcheck
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $username
 * @property string $attr
 * @property string $op
 * @property string $value
 * @property integer $id_accseries
 * @property AccAccseries $AccAccseries
 * 
 * @method integer      getId()           Returns the current record's "id" value
 * @method string       getUsername()     Returns the current record's "username" value
 * @method string       getAttr()         Returns the current record's "attr" value
 * @method string       getOp()           Returns the current record's "op" value
 * @method string       getValue()        Returns the current record's "value" value
 * @method integer      getIdAccseries()  Returns the current record's "id_accseries" value
 * @method AccAccseries getAccAccseries() Returns the current record's "AccAccseries" value
 * @method Radcheck     setId()           Sets the current record's "id" value
 * @method Radcheck     setUsername()     Sets the current record's "username" value
 * @method Radcheck     setAttr()         Sets the current record's "attr" value
 * @method Radcheck     setOp()           Sets the current record's "op" value
 * @method Radcheck     setValue()        Sets the current record's "value" value
 * @method Radcheck     setIdAccseries()  Sets the current record's "id_accseries" value
 * @method Radcheck     setAccAccseries() Sets the current record's "AccAccseries" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRadcheck extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('radcheck');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'radcheck_id',
             'length' => 4,
             ));
        $this->hasColumn('username', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('attr', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('op', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '==',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('value', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('id_accseries', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AccAccseries', array(
             'local' => 'id_accseries',
             'foreign' => 'id'));
    }
}