<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AccSubscriberinfo', 'doctrine');

/**
 * BaseAccSubscriberinfo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $username
 * @property string $name
 * @property integer $id_isporg
 * @property string $address
 * @property string $city
 * @property string $phone
 * @property string $email
 * @property integer $id_accseries
 * @property AccAccseries $AccAccseries
 * 
 * @method integer           getId()           Returns the current record's "id" value
 * @method string            getUsername()     Returns the current record's "username" value
 * @method string            getName()         Returns the current record's "name" value
 * @method integer           getIdIsporg()     Returns the current record's "id_isporg" value
 * @method string            getAddress()      Returns the current record's "address" value
 * @method string            getCity()         Returns the current record's "city" value
 * @method string            getPhone()        Returns the current record's "phone" value
 * @method string            getEmail()        Returns the current record's "email" value
 * @method integer           getIdAccseries()  Returns the current record's "id_accseries" value
 * @method AccAccseries      getAccAccseries() Returns the current record's "AccAccseries" value
 * @method AccSubscriberinfo setId()           Sets the current record's "id" value
 * @method AccSubscriberinfo setUsername()     Sets the current record's "username" value
 * @method AccSubscriberinfo setName()         Sets the current record's "name" value
 * @method AccSubscriberinfo setIdIsporg()     Sets the current record's "id_isporg" value
 * @method AccSubscriberinfo setAddress()      Sets the current record's "address" value
 * @method AccSubscriberinfo setCity()         Sets the current record's "city" value
 * @method AccSubscriberinfo setPhone()        Sets the current record's "phone" value
 * @method AccSubscriberinfo setEmail()        Sets the current record's "email" value
 * @method AccSubscriberinfo setIdAccseries()  Sets the current record's "id_accseries" value
 * @method AccSubscriberinfo setAccAccseries() Sets the current record's "AccAccseries" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAccSubscriberinfo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('acc_subscriberinfo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'acc_subscriberinfo_id',
             'length' => 4,
             ));
        $this->hasColumn('username', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('id_isporg', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('address', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('city', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('phone', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('email', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('id_accseries', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AccAccseries', array(
             'local' => 'id_accseries',
             'foreign' => 'id'));
    }
}