<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AccPostpaccount', 'doctrine');

/**
 * BaseAccPostpaccount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $username
 * @property integer $id_isporg
 * @property integer $id_ispsuborg
 * @property integer $id_accseries
 * @property string $ind_active
 * @property AccAccseries $AccAccseries
 * @property AccIsporg $AccIsporg
 * @property AccIspsuborg $AccIspsuborg
 * @property Doctrine_Collection $AccPostpaccountlog
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method string              getUsername()           Returns the current record's "username" value
 * @method integer             getIdIsporg()           Returns the current record's "id_isporg" value
 * @method integer             getIdIspsuborg()        Returns the current record's "id_ispsuborg" value
 * @method integer             getIdAccseries()        Returns the current record's "id_accseries" value
 * @method string              getIndActive()          Returns the current record's "ind_active" value
 * @method AccAccseries        getAccAccseries()       Returns the current record's "AccAccseries" value
 * @method AccIsporg           getAccIsporg()          Returns the current record's "AccIsporg" value
 * @method AccIspsuborg        getAccIspsuborg()       Returns the current record's "AccIspsuborg" value
 * @method Doctrine_Collection getAccPostpaccountlog() Returns the current record's "AccPostpaccountlog" collection
 * @method AccPostpaccount     setId()                 Sets the current record's "id" value
 * @method AccPostpaccount     setUsername()           Sets the current record's "username" value
 * @method AccPostpaccount     setIdIsporg()           Sets the current record's "id_isporg" value
 * @method AccPostpaccount     setIdIspsuborg()        Sets the current record's "id_ispsuborg" value
 * @method AccPostpaccount     setIdAccseries()        Sets the current record's "id_accseries" value
 * @method AccPostpaccount     setIndActive()          Sets the current record's "ind_active" value
 * @method AccPostpaccount     setAccAccseries()       Sets the current record's "AccAccseries" value
 * @method AccPostpaccount     setAccIsporg()          Sets the current record's "AccIsporg" value
 * @method AccPostpaccount     setAccIspsuborg()       Sets the current record's "AccIspsuborg" value
 * @method AccPostpaccount     setAccPostpaccountlog() Sets the current record's "AccPostpaccountlog" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAccPostpaccount extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('acc_postpaccount');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'acc_postpaccount_id',
             'length' => 4,
             ));
        $this->hasColumn('username', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('id_isporg', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_ispsuborg', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_accseries', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ind_active', 'string', null, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'default' => '0',
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AccAccseries', array(
             'local' => 'id_accseries',
             'foreign' => 'id'));

        $this->hasOne('AccIsporg', array(
             'local' => 'id_isporg',
             'foreign' => 'id'));

        $this->hasOne('AccIspsuborg', array(
             'local' => 'id_ispsuborg',
             'foreign' => 'id'));

        $this->hasMany('AccPostpaccountlog', array(
             'local' => 'id',
             'foreign' => 'id_postpaccount'));
    }
}