[en]

ispused_user = ERROR Can not delete. Specified ISP contains users
ispused_def = ERROR Can not delete. Specified ISP contains contains definitions
ispused_suborg = ERROR Can not delete. Specified ISP contains contains SUBORGS
image_jpg = Image needs to be in JPG format

[hr]

ispused_user = ERROR Can not delete. Specified ISP contains users
ispused_def = ERROR Can not delete. Specified ISP contains contains definitions
ispused_suborg = ERROR Can not delete. Specified ISP contains contains SUBORGS
image_jpg = Image needs to be in JPG format