[en]
no_data = No data to display. Please choose different graph parameters.
toomuch_data = Too much data. Please choose smaller interval.
preptraff = PREPAID traffic for interval
posttraff = POSTPAID traffic for interval


[hr]
no_data = No data to display. Please choose different graph parameters.
toomuch_data = Too much data. Please choose smaller interval.
preptraff = PREPAID promet za interval
posttraff = PPOSTPAID promet za interval

