[en]

ok_del = records deleted successfully
err_del = Operation failed
ok_mail = email sent
err_mail = error sending email
records_cleaned = records cleaned
ok_index = daabase reindexed
err_index = database could not be reindexed
ok_radres = radius server restarted
err_radres =  could not restart radius server
no_action = action not specified
ok_upgrade = new system version installed
no_upgrade = there is no new system version available

[hr]

ok_del = records deleted successfully
err_del = Operation failed
ok_mail = email sent
err_mail = error sending email
records_cleaned = records cleaned
ok_index = daabase reindexed
err_index = database could not be reindexed
ok_radres = radius server restarted
err_radres =  could not restart radius server
no_action = action not specified
ok_upgrade = new system version installed
no_upgrade = there is no new system version available
