[en]

nouser = User does not exists
nochangesysuser = not enough privilegies to change sysadmin password
otherisp = can not change user passwords for other ISP
passnoequal = password does not match
upd_ok = password updated
upd_no_ok = error updating password

[hr]

nouser = User does not exists
nochangesysuser = not enough privilegies to change sysadmin password
otherisp = can not change user passwords for other ISP
passnoequal = password does not match
upd_ok = password updated
upd_no_ok = error updating password

