[en]

username = username
nrbill = NR bill
print = print
mu = mesure unit
bu = billing unit
buprice = price BU
date = date
buspent = BU spent
totalprice = total
billlist = bill list
issuedby = issued by

[hr]

username = korisnik
nrbill = BR računa
print = ispis
mu = mjerna jed
bu = obračunska jed
buprice = price OJ
date = datum
buspent = OJ potrošeno
totalprice = total
billlist = lista računa
issuedby = izdao