[en]
active = User successfully activated
failactive = ERROR: User unsuccessfully activated
deactive = User successfully deactivated
faildeactive = ERROR: User unsuccessfully deactivated
nouser = ERROR:  User does not exists

username = username
manageuser= Manage user
billingdata = Billing data
print = print
mu = mesure unit
bu = billing unit
pricebu = BU price
buspent = BU spent
startprice = start price
totalprice = total



[hr]
active = Korisnik uspijšeno aktiviran
failactive = ERR Aktivacija nije uspijela
deactive = Korisnik uspiješno deaktiviran
faildeactive =ERR Deaktivacija nije uspijela
nouser = ERR Korisnik ne postoji

username = korisničko ime
manageuser= Rad sa korisnicima
billingdata = Lista podataka
print = ispis
mu = mjerna jed
bu = obračunska jed
pricebu = price OJ
buspent = OJ potrošeno
startprice = početna cijena
totalprice = total