[en]
ok_del = Saled card deleted successfully
err_del = Operation FAILED
err_input = Input ERROR
ok_sold = Card SOLD
err_sold = Operation ERROR

username = username
print = print
saledate = sale date
definition = definition
price = price
issuedby = issued by
accounts = accounts
issuedcards = issued cards
stornaccount = storn account

[hr]
ok_del = Kartica uspješno stornirana
err_del = Operacija nije uspjela
err_input = Pogriješka u unosu
ok_sold = Kartica prodana
err_sold = Operacija nije uspjela

username = korisničko ime
print = ispis
saledate = datum prodaje
definition = definicija
price = cijena
issuedby = izdao
accounts = preostalo
issuedcards = izdate kartice
stornaccount = storno korisnika