<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/05/11 14:22:55

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=ipacct_radius',
  'username' => 'postgres',
  'password' => '11hack11',
  'name' => 'doctrine',
)),);
