# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        IPACCT Administration
    #description:  Radius Web Interface
    #keywords:     primus, ipacct
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css]

  javascripts:    [main_menu.js]

  has_layout:     true
  layout:         layout
