<?php

/*
Generated By PHP Konsole
on primus [Apache/2.0.52 (Fedora)]
at Fri, 26 May 2006 10:39:58 +0200
*/

require_once('framework.php');

$sec = new cIpacct();
if($sec->isLoggedIn('administrator')!=LOGIN_PASSED)
	header('Location: login.php');
ob_end_flush();

$hdr = new cReplace('header');
$tpl = new cReplace;
$ftr = new cReplace('footer');

$hdr->replace('#topnav','#');
$session=$sec->getSession('user_info');
include_once('include/common_var');
$mess = new cMessage($s_lang);

$opts=$sec->fetchAllowedISP();
$tpl->dropDown('#isporg',$opts,$p_isporg,true);

if($p_loop==0) $p_isporg=$s_id_isporg;
if($p_loop==1)
{
  $front=ereg_replace("(^<!--|-->$)",null,stripslashes(trim($p_front)));
  $back=ereg_replace("(^<!--|-->$)",null,stripslashes(trim($p_back)));
  $sec->writeFile("template/isp/$p_isporg/inSingleCard.tpl",$front);
  $sec->writeFile("template/isp/$p_isporg/outSingleCard.tpl",$back);
  $hdr->replace("#message",SAVED);
}

$frontFile=$sec->openFile("template/isp/$p_isporg/inSingleCard.tpl");
$backFile=$sec->openFile("template/isp/$p_isporg/outSingleCard.tpl");

$tpl->replace("#front",$frontFile);
$tpl->replace("#back",$backFile);

$hdr->render();
$tpl->render(false);
$ftr->render();

?>
