<?php

/*
Generated By PHP Konsole
on primus [Apache/2.0.52 (Fedora)]
at Fri, 26 May 2006 10:39:58 +0200
*/

require_once('framework.php');
require_once('include/cMailer.php');

$base = new cBase('sysStatus');
$tpl = new cReplace;
$mail = new cMailer;

$session=$base->getSession('user_info');

$s_id_user=trim($session['id']);
$s_orgname=$session['orgname'];
$s_email_nasadmin=$session['email_nasadmin'];
$s_lang=$session['lang'];

$mess = new cMessage($s_lang,'sysStatus',$tpl);

$param=array($g_isporg,$g_isporg,$g_isporg);

$exec=$base->execute('sel_nas',$param);
$rows=$base->fetchAll();

$users=0;
$online=$base->getSession('online');
if(!is_array($online))
  $online=array();

foreach($rows as $id => $record)
{
    $ipaddress=trim($record['nasname']);
    $resolvaddr=gethostbyname($ipaddress);
    $shortname=$record['shortname'];
    $adminport=$record['pacc_adminport'];
    $curr=$online[$shortname];
   if(strlen($record['mac']) > 15 && strlen(trim($record['pacc_macaddress'])) == 0)
   {
     $rows[$id]['pacc_nasipaddress']=$resolvaddr;
     $param=array($resolvaddr,$record['id']);
     $exec=$base->execute('upd_address',$param);
   }

    if(!$curr) $curr=0;

    $rows[$id]['status']='red';
    $rows[$id]['naslink']='#';

    $cmd='ping -c 1 -w 1 '.$ipaddress;
    $len=exec($cmd);
    if(strlen($len)>0)
    {
      $rows[$id]['status']='green';
      $curr=0;
    }
    if($adminport > 0)
    {

      $sock = socket_create(AF_INET, SOCK_STREAM, SOL_TCP);
      socket_set_nonblock($sock);
      @socket_connect($sock,$ipaddress,$adminport);
      socket_set_block($sock);
      $conn=socket_select($r=array($sock),$w=array($sock),$f=array($sock),1);
      if($conn==1)
      {
        $rows[$id]['status']='green';
        $curr=0;

        $naslink='http://'.$ipaddress.':'.$adminport;
        $rows[$id]['naslink']="window.open('$naslink',null,'width=800,height=600,menubar=no,scrollbars=yes')";
      }
    }
    if($rows[$id]['status']=='red')
    {
        $curr++;
        if($curr==1 && $base->getGlobal('ind_send_alert') && ereg("@",$s_email_nasadmin))
        {
    	  $mail->IsSMTP();                                      // set mailer to use SMTP
	  $mail->Host = $base->getGlobal('mailserver');
	  $mail->CharSet = "iso-8859-2";
	  $mail->From = $base->getGlobal('mailfromaddr');
	  $mail->FromName = $base->getGlobal('mailfromname');
	  $mail->AddAddress($s_email_nasadmin);
	  $mail->IsHTML(false);
	  $mail->Subject = "NAS offline";
	  $mail->Body = "$s_orgname/$shortname/$ipaddress";
	  if(!$mail->Send())
          {
            $errfile=DUMPDIR."mailer.dump";
            $errtext=$mail->ErrorInfo."\n";
            $base->writeFile($errfile,$errtext,true);
          }
          $mail->ClearAddresses();
        }
     }
   $online[$shortname]=$curr;
   $users+=$rows[$id]['users'];
}
$base->setSession('online',$online);
$tpl->replace("#now",date("l d.m.Y H:i:s"));

$tpl->loop(1,$rows);

$tpl->render();

?>
