<?php

/*
Generated By PHP Konsole
on primus [Apache/2.0.52 (Fedora)]
at Fri, 26 May 2006 10:39:58 +0200
*/

require_once('framework.php');

$tpl = new cReplace;
$sec = new cIpacct;
$base = new cBase("onlineUsers");

$param=array($_SESSION['isp']);
$exec=$base->execute('list_users',$param);

$rows=$base->fetchAll();

foreach($rows as $id => $record)
{
    $rows[$id]['acctstarttime']=date("H:i:s  d/m", strtotime($record['acctstarttime']));
    $rows[$id]['acctsessiontime']=$sec->time2str($record['acctsessiontime']);
    $rows[$id]['traffic']=$sec->bytes2str($record['traffic']);
    $rows[$id]['nasipaddress']=gethostbyaddr($record['nasipaddress']);
}
$tpl->loop(1,$rows);

$nruser=count($rows);
$tpl->setSession("numonlineusers",$nruser);

$tpl->render();

?>
