<?php

/*
Generated By PHP Konsole
on primus [Apache/2.0.52 (Fedora)]
at Fri, 26 May 2006 10:33:58 +0200
*/

require_once('framework.php');

$sec = new cIpacct();
if($sec->isLoggedIn('operator')!=LOGIN_PASSED)
	header('Location: login.php');
ob_end_flush();

$base = new cBase;
$hdr = new cReplace('header');
$tpl = new cReplace;
$ftr = new cReplace('footer');

$hdr->replace('#topnav','#');
$session=$sec->getSession('user_info');
include_once('include/common_var');
$mess = new cMessage($s_lang,0,$tpl);

if($s_usertype=='administrator')
{
  if($s_id_user==1)
    $c_username='%-%-'.$p_username.'%';
  else
    $c_username=$s_id_isporg.'-%-'.$p_username.'%';
} else {
  $c_username=$s_id_isporg.'-'.$s_id_ispsuborg.'-'.$p_username.'%';
}

$param=array( $c_username,$c_username );
$exec=$base->execute('sel_s_bill',$param);
$rows=$base->fetchAll();

foreach($rows as $id => $record)
{
  if($s_usertype !='administrator')
  {  
    $tmp_user=explode('-',$record['username']);
    $rows[$id]['username']=$tmp_user[2];
  }
  $rows[$id]['srvstoptime']=date("H:i:s  d/m", strtotime($record['srvstoptime']));
  $rows[$id]['totalprice']=($record['buspent']*$record['pricebillingunit'])+$record['priceonstart'];
  $rows[$id]['totalprice']=number_format($rows[$id]['totalprice'],2,".","");
  if(strlen(trim($record['buspent']))==0)
      $rows[$id]['buspent']='0';
}
	  
$tpl->loop(1,$rows);

$hdr->render();
$tpl->render();
$ftr->render();

?>
